#############################################################
#####                    Data upload                    #####
#############################################################
# This code is to upload the data related to the number of fibres generated by ImageJ
# The .csv file to upload will need to have the following columns:
# Slice; Count;
# "Count" correspond to the fibre counted by imageJ

# "Slice" correspond to the name of the receiver swatch and must be written in this form "W000_G1_G3_8_perp_B.TIF" for the wash experiments
# with Wxxx the wash number, Gx the garment number, "_x_" the contact area number and "_B" the condition of the experimentr
# condition experiments: "B" for Before transfer, "Atr" for after transfer

# ------------------------------------------------------------------------
# Section 1: Impact test and Repeated Contact
# ------------------------------------------------------------------------
# Read the CSV file containing garment weight data
ImpactTest <- read.csv('./Data/Impact-test_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
ImpactTest$Slice<- gsub(".TIF","",ImpactTest$Slice)
ImpactTest_Extended <- data.frame(str_split(ImpactTest$Slice, "_", simplify=TRUE))
names(ImpactTest_Extended) <- c("Project","Experiment","Garment","Height","Repeat")
ImpactTest <- cbind(ImpactTest_Extended,Area=ImpactTest$Total.Area)
rm(ImpactTest_Extended)

RepeatedContact<- read.csv('./Data/Repeated-contact_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
RepeatedContact$Slice<- gsub(".TIF","",RepeatedContact$Slice)
RepeatedContact_Extended <- data.frame(str_split(RepeatedContact$Slice, "_", simplify=TRUE))
RepeatedContact <- data.frame(cbind(Contact.Area=RepeatedContact_Extended$X4,Repeat=RepeatedContact_Extended$X5,Area=RepeatedContact$Total.Area))
RepeatedContact$Area <- as.numeric(RepeatedContact$Area)
rm(RepeatedContact_Extended)

# ------------------------------------------------------------------------
# Section 2: Shedding data from washed garments
# ------------------------------------------------------------------------
# Read the CSV file containing garment weight data
Shedding_G1 <- read.csv('./Data/SH_Garment1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
Shedding_G1$Slice<- gsub(".TIF","",Shedding_G1$Slice)
Shedding_G1_Extended <- data.frame(str_split(Shedding_G1$Slice, "_", simplify=TRUE))
names(Shedding_G1_Extended) <- c("Project","Wash","Garment","Weight","Repeat")
Shedding_G1 <- cbind(Shedding_G1_Extended,Area=Shedding_G1$Total.Area)
rm(Shedding_G1_Extended)

Shedding_G2 <- read.csv('./Data/SH_Garment2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
Shedding_G2$Slice<- gsub(".TIF","",Shedding_G2$Slice)
Shedding_G2_Extended <- data.frame(str_split(Shedding_G2$Slice, "_", simplify=TRUE))
names(Shedding_G2_Extended) <- c("Project","Wash","Garment","Weight","Repeat")
Shedding_G2 <- cbind(Shedding_G2_Extended,Area=Shedding_G2$Total.Area)
rm(Shedding_G2_Extended)

Shedding_G3 <- read.csv('./Data/SH_Garment3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
Shedding_G3$Slice<- gsub(".TIF","",Shedding_G3$Slice)
Shedding_G3_Extended <- data.frame(str_split(Shedding_G3$Slice, "_", simplify=TRUE))
names(Shedding_G3_Extended) <- c("Project","Wash","Garment","Weight","Repeat")
Shedding_G3 <- cbind(Shedding_G3_Extended,Area=Shedding_G3$Total.Area)
rm(Shedding_G3_Extended)

Shedding_G4 <- read.csv('./Data/SH_Garment4_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
Shedding_G4$Slice<- gsub(".TIF","",Shedding_G4$Slice)
Shedding_G4_Extended <- data.frame(str_split(Shedding_G4$Slice, "_", simplify=TRUE))
names(Shedding_G4_Extended) <- c("Project","Wash","Garment","Weight","Repeat")
Shedding_G4 <- cbind(Shedding_G4_Extended,Area=Shedding_G4$Total.Area)
rm(Shedding_G4_Extended)

# ------------------------------------------------------------------------
# Section 3: Transfer experiments
# ------------------------------------------------------------------------
#### Uploading data from the first series involving washing a single donor garment ####
G1 <- read.csv('./Data/Transfer_Garment1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')

# Remove ".TIF" in G1
G1$Slice<- gsub(".TIF","",G1$Slice)

# Remove "_negative" and "_positive" in G1
text_to_remove <- "_negative"
G1 <- G1[!grepl(text_to_remove, G1$Slice), ]
text_to_remove <- "_positive"
G1 <- G1[!grepl(text_to_remove, G1$Slice), ]

# Create different dataframes before and after transfer
G1B<- G1 %>% filter(grepl('_B', Slice))
G1Atr <- G1 %>% filter(grepl('_Atr', Slice))

# Create table
G1_Dataset_pending <- data.frame(rbind(G1B$Slice, G1B$Count, G1Atr$Count))
G1_Dataset<-as.data.frame(t(G1_Dataset_pending))

names(G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# Convert factor to numeric in columns 2 to 3
G1_Dataset[,2:3] = apply(G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# Remove unused dataframes
rm(G1,G1B,G1Atr,G1_Dataset_pending)

#### Uploading data from the first series involving washing a single donor garment with detergent ####
G2 <- read.csv('./Data/Transfer_Garment2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')

# Remove ".TIF" in G2
G2$Slice<- gsub(".TIF","",G2$Slice)

# Remove "_negative" and "_positive" in G2
text_to_remove <- "_negative"
G2 <- G2[!grepl(text_to_remove, G2$Slice), ]
text_to_remove <- "_positive"
G2 <- G2[!grepl(text_to_remove, G2$Slice), ]

# Create different dataframes before and after transfer
G2B<- G2 %>% filter(grepl('_B', Slice))
G2Atr <- G2 %>% filter(grepl('_Atr', Slice))

# Create table
G2_Dataset_pending <- data.frame(rbind(G2B$Slice, G2B$Count, G2Atr$Count))
G2_Dataset<-as.data.frame(t(G2_Dataset_pending))

names(G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# Convert factor to numeric in columns 2 to 3
G2_Dataset[,2:3] = apply(G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# Remove unused dataframes
rm(G2,G2B,G2Atr,G2_Dataset_pending)

#### Uploading data from the first series involving washing a single donor garment with detergent and softener ####
G3 <- read.csv('./Data/Transfer_Garment3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')

# Remove ".TIF" in G3
G3$Slice<- gsub(".TIF","",G3$Slice)

# Remove "_negative" and "_positive" in G3
text_to_remove <- "_negative"
G3 <- G3[!grepl(text_to_remove, G3$Slice), ]
text_to_remove <- "_positive"
G3 <- G3[!grepl(text_to_remove, G3$Slice), ]

# Create different dataframes before and after transfer
G3B<- G3 %>% filter(grepl('_B', Slice))
G3Atr <- G3 %>% filter(grepl('_Atr', Slice))

# Create table
G3_Dataset_pending <- data.frame(rbind(G3B$Slice, G3B$Count, G3Atr$Count))
G3_Dataset<-as.data.frame(t(G3_Dataset_pending))

names(G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# Convert factor to numeric in columns 2 to 3
G3_Dataset[,2:3] = apply(G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# Remove unused dataframes
rm(G3,G3B,G3Atr,G3_Dataset_pending)

#### Uploading data from the third series involving washing 12 donor garments ####
G12 <- read.csv('./Data/Transfer_Garment12_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')

# Remove ".TIF" in G12
G12$Slice<- gsub(".TIF","",G12$Slice)

# Remove "_negative" and "_positive" in G12
text_to_remove <- "_negative"
G12 <- G12[!grepl(text_to_remove, G12$Slice), ]
text_to_remove <- "_positive"
G12 <- G12[!grepl(text_to_remove, G12$Slice), ]

# Create different dataframes before and after transfer
G12B<- G12 %>% filter(grepl('_B', Slice))
G12Atr <- G12 %>% filter(grepl('_Atr', Slice))

# Create table
G12_Dataset_pending <- data.frame(rbind(G12B$Slice, G12B$Count, G12Atr$Count))
G12_Dataset<-as.data.frame(t(G12_Dataset_pending))

names(G12_Dataset) <- c("Sample", "Before transfer", "After transfer")

# Convert factor to numeric in columns 2 to 3
G12_Dataset[,2:3] = apply(G12_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# Remove unused dataframes
rm(G12,G12B,G12Atr,G12_Dataset_pending)
