#############################################################
#####                    Data upload                    #####
#############################################################
# This code is to upload the data related to the number of fibres generated by ImageJ
# The .csv file to upload will need to have the following columns:
# Slice; Count;
# "Count" correspond to the fibre counted by imageJ

# "Slice" correspond to the name of the receiver swatch and must be written in this form "W000_G3_8_perp_B.TIF" for the wash experiments
# with Wxxx the wash number, Gx the garment number, "_x_" the contact area number and "_B" the condition of the experimentr
# condition experiments: "B" for Before transfer, "Atr" for after transfer

#############################################################
#####          Washed Garment - Repetitive wash         #####
#############################################################
#-----------------------------------------------------------#
#####                         W000                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000 <- read.csv('./Fibre count Summary/W000_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000B <- W000 %>% filter(grepl('_B.', Slice))
W000Atr <- W000 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000B and W000Atr
W000B$Slice<- gsub(".TIF","",W000B$Slice)
W000Atr$Slice<- gsub(".TIF","",W000Atr$Slice)

# Create table
W000_Dataset_pending <- data.frame(rbind(W000B$Slice, W000B$Count, W000Atr$Count))
W000_Dataset<-as.data.frame(t(W000_Dataset_pending))
names(W000_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_Dataset[,2:3] = apply(W000_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000,W000B,W000Atr,W000_Dataset_pending)

#-----------------------------------------------------------#
#####                         W001                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001 <- read.csv('./Fibre count Summary/W001_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001B <- W001 %>% filter(grepl('_B.', Slice))
W001Atr <- W001 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001B and W001Atr
W001B$Slice<- gsub(".TIF","",W001B$Slice)
W001Atr$Slice<- gsub(".TIF","",W001Atr$Slice)

# Create table
W001_Dataset_pending <- data.frame(rbind(W001B$Slice, W001B$Count, W001Atr$Count))
W001_Dataset<-as.data.frame(t(W001_Dataset_pending))
names(W001_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_Dataset[,2:3] = apply(W001_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001,W001B,W001Atr,W001_Dataset_pending)

#-----------------------------------------------------------#
#####                         W002                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002 <- read.csv('./Fibre count Summary/W002_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002B <- W002 %>% filter(grepl('_B.', Slice))
W002Atr <- W002 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002B and W002Atr
W002B$Slice<- gsub(".TIF","",W002B$Slice)
W002Atr$Slice<- gsub(".TIF","",W002Atr$Slice)

# Create table
W002_Dataset_pending <- data.frame(rbind(W002B$Slice, W002B$Count, W002Atr$Count))
W002_Dataset<-as.data.frame(t(W002_Dataset_pending))
names(W002_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_Dataset[,2:3] = apply(W002_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002,W002B,W002Atr,W002_Dataset_pending)

#-----------------------------------------------------------#
#####                         W003                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003 <- read.csv('./Fibre count Summary/W003_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003B <- W003 %>% filter(grepl('_B.', Slice))
W003Atr <- W003 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003B and W003Atr
W003B$Slice<- gsub(".TIF","",W003B$Slice)
W003Atr$Slice<- gsub(".TIF","",W003Atr$Slice)

# Create table
W003_Dataset_pending <- data.frame(rbind(W003B$Slice, W003B$Count, W003Atr$Count))
W003_Dataset<-as.data.frame(t(W003_Dataset_pending))
names(W003_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_Dataset[,2:3] = apply(W003_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003,W003B,W003Atr,W003_Dataset_pending)

#-----------------------------------------------------------#
#####                         W004                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004 <- read.csv('./Fibre count Summary/W004_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004B <- W004 %>% filter(grepl('_B.', Slice))
W004Atr <- W004 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004B and W004Atr
W004B$Slice<- gsub(".TIF","",W004B$Slice)
W004Atr$Slice<- gsub(".TIF","",W004Atr$Slice)

# Create table
W004_Dataset_pending <- data.frame(rbind(W004B$Slice, W004B$Count, W004Atr$Count))
W004_Dataset<-as.data.frame(t(W004_Dataset_pending))
names(W004_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_Dataset[,2:3] = apply(W004_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004,W004B,W004Atr,W004_Dataset_pending)

#-----------------------------------------------------------#
#####                         W005                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005 <- read.csv('./Fibre count Summary/W005_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005B <- W005 %>% filter(grepl('_B.', Slice))
W005Atr <- W005 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005B and W005Atr
W005B$Slice<- gsub(".TIF","",W005B$Slice)
W005Atr$Slice<- gsub(".TIF","",W005Atr$Slice)

# Create table
W005_Dataset_pending <- data.frame(rbind(W005B$Slice, W005B$Count, W005Atr$Count))
W005_Dataset<-as.data.frame(t(W005_Dataset_pending))
names(W005_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_Dataset[,2:3] = apply(W005_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005,W005B,W005Atr,W005_Dataset_pending)