#############################################################
#####                    Data upload                    #####
#############################################################
# This code is to upload the data related to the number of fibres generated by ImageJ
# The .csv file to upload will need to have the following columns:
# Slice; Count;
# "Count" correspond to the fibre counted by imageJ

# "Slice" correspond to the name of the receiver swatch and must be written in this form "W000_G1_G3_8_perp_B.TIF" for the wash experiments
# with Wxxx the wash number, Gx the garment number, "_x_" the contact area number and "_B" the condition of the experimentr
# condition experiments: "B" for Before transfer, "Atr" for after transfer

#############################################################
#####             GARMENT 1 - NO DERTERGENT             #####
#############################################################
#-----------------------------------------------------------#
#####                     W000_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G1 <- read.csv('./Fibre count Summary/W000_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G1B <- W000_G1 %>% filter(grepl('_B.', Slice))
W000_G1Atr <- W000_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G1B and W000_G1Atr
W000_G1B$Slice<- gsub(".TIF","",W000_G1B$Slice)
W000_G1Atr$Slice<- gsub(".TIF","",W000_G1Atr$Slice)

# Create table
W000_G1_Dataset_pending <- data.frame(rbind(W000_G1B$Slice, W000_G1B$Count, W000_G1Atr$Count))
W000_G1_Dataset<-as.data.frame(t(W000_G1_Dataset_pending))
names(W000_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G1_Dataset[,2:3] = apply(W000_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G1,W000_G1B,W000_G1Atr,W000_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W001_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G1 <- read.csv('./Fibre count Summary/W001_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G1B <- W001_G1 %>% filter(grepl('_B.', Slice))
W001_G1Atr <- W001_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G1B and W001_G1Atr
W001_G1B$Slice<- gsub(".TIF","",W001_G1B$Slice)
W001_G1Atr$Slice<- gsub(".TIF","",W001_G1Atr$Slice)

# Create table
W001_G1_Dataset_pending <- data.frame(rbind(W001_G1B$Slice, W001_G1B$Count, W001_G1Atr$Count))
W001_G1_Dataset<-as.data.frame(t(W001_G1_Dataset_pending))
names(W001_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G1_Dataset[,2:3] = apply(W001_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G1,W001_G1B,W001_G1Atr,W001_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W002_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G1 <- read.csv('./Fibre count Summary/W002_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G1B <- W002_G1 %>% filter(grepl('_B.', Slice))
W002_G1Atr <- W002_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G1B and W002_G1Atr
W002_G1B$Slice<- gsub(".TIF","",W002_G1B$Slice)
W002_G1Atr$Slice<- gsub(".TIF","",W002_G1Atr$Slice)

# Create table
W002_G1_Dataset_pending <- data.frame(rbind(W002_G1B$Slice, W002_G1B$Count, W002_G1Atr$Count))
W002_G1_Dataset<-as.data.frame(t(W002_G1_Dataset_pending))
names(W002_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G1_Dataset[,2:3] = apply(W002_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G1,W002_G1B,W002_G1Atr,W002_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W003_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G1 <- read.csv('./Fibre count Summary/W003_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G1B <- W003_G1 %>% filter(grepl('_B.', Slice))
W003_G1Atr <- W003_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G1B and W003_G1Atr
W003_G1B$Slice<- gsub(".TIF","",W003_G1B$Slice)
W003_G1Atr$Slice<- gsub(".TIF","",W003_G1Atr$Slice)

# Create table
W003_G1_Dataset_pending <- data.frame(rbind(W003_G1B$Slice, W003_G1B$Count, W003_G1Atr$Count))
W003_G1_Dataset<-as.data.frame(t(W003_G1_Dataset_pending))
names(W003_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G1_Dataset[,2:3] = apply(W003_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G1,W003_G1B,W003_G1Atr,W003_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W004_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G1 <- read.csv('./Fibre count Summary/W004_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G1B <- W004_G1 %>% filter(grepl('_B.', Slice))
W004_G1Atr <- W004_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G1B and W004_G1Atr
W004_G1B$Slice<- gsub(".TIF","",W004_G1B$Slice)
W004_G1Atr$Slice<- gsub(".TIF","",W004_G1Atr$Slice)

# Create table
W004_G1_Dataset_pending <- data.frame(rbind(W004_G1B$Slice, W004_G1B$Count, W004_G1Atr$Count))
W004_G1_Dataset<-as.data.frame(t(W004_G1_Dataset_pending))
names(W004_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G1_Dataset[,2:3] = apply(W004_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G1,W004_G1B,W004_G1Atr,W004_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W005_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G1 <- read.csv('./Fibre count Summary/W005_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G1B <- W005_G1 %>% filter(grepl('_B.', Slice))
W005_G1Atr <- W005_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G1B and W005_G1Atr
W005_G1B$Slice<- gsub(".TIF","",W005_G1B$Slice)
W005_G1Atr$Slice<- gsub(".TIF","",W005_G1Atr$Slice)

# Create table
W005_G1_Dataset_pending <- data.frame(rbind(W005_G1B$Slice, W005_G1B$Count, W005_G1Atr$Count))
W005_G1_Dataset<-as.data.frame(t(W005_G1_Dataset_pending))
names(W005_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G1_Dataset[,2:3] = apply(W005_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G1,W005_G1B,W005_G1Atr,W005_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W006_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G1 <- read.csv('./Fibre count Summary/W006_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G1B <- W006_G1 %>% filter(grepl('_B.', Slice))
W006_G1Atr <- W006_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G1B and W006_G1Atr
W006_G1B$Slice<- gsub(".TIF","",W006_G1B$Slice)
W006_G1Atr$Slice<- gsub(".TIF","",W006_G1Atr$Slice)

# Create table
W006_G1_Dataset_pending <- data.frame(rbind(W006_G1B$Slice, W006_G1B$Count, W006_G1Atr$Count))
W006_G1_Dataset<-as.data.frame(t(W006_G1_Dataset_pending))
names(W006_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G1_Dataset[,2:3] = apply(W006_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G1,W006_G1B,W006_G1Atr,W006_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W007_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W007_G1 <- read.csv('./Fibre count Summary/W007_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W007_G1B <- W007_G1 %>% filter(grepl('_B.', Slice))
W007_G1Atr <- W007_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W007_G1B and W007_G1Atr
W007_G1B$Slice<- gsub(".TIF","",W007_G1B$Slice)
W007_G1Atr$Slice<- gsub(".TIF","",W007_G1Atr$Slice)

# Create table
W007_G1_Dataset_pending <- data.frame(rbind(W007_G1B$Slice, W007_G1B$Count, W007_G1Atr$Count))
W007_G1_Dataset<-as.data.frame(t(W007_G1_Dataset_pending))
names(W007_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W007_G1_Dataset[,2:3] = apply(W007_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W007_G1,W007_G1B,W007_G1Atr,W007_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W009_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W009_G1 <- read.csv('./Fibre count Summary/W009_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W009_G1B <- W009_G1 %>% filter(grepl('_B.', Slice))
W009_G1Atr <- W009_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W009_G1B and W009_G1Atr
W009_G1B$Slice<- gsub(".TIF","",W009_G1B$Slice)
W009_G1Atr$Slice<- gsub(".TIF","",W009_G1Atr$Slice)

# Create table
W009_G1_Dataset_pending <- data.frame(rbind(W009_G1B$Slice, W009_G1B$Count, W009_G1Atr$Count))
W009_G1_Dataset<-as.data.frame(t(W009_G1_Dataset_pending))
names(W009_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W009_G1_Dataset[,2:3] = apply(W009_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W009_G1,W009_G1B,W009_G1Atr,W009_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W011_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W011_G1 <- read.csv('./Fibre count Summary/W011_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W011_G1B <- W011_G1 %>% filter(grepl('_B.', Slice))
W011_G1Atr <- W011_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W011_G1B and W011_G1Atr
W011_G1B$Slice<- gsub(".TIF","",W011_G1B$Slice)
W011_G1Atr$Slice<- gsub(".TIF","",W011_G1Atr$Slice)

# Create table
W011_G1_Dataset_pending <- data.frame(rbind(W011_G1B$Slice, W011_G1B$Count, W011_G1Atr$Count))
W011_G1_Dataset<-as.data.frame(t(W011_G1_Dataset_pending))
names(W011_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W011_G1_Dataset[,2:3] = apply(W011_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W011_G1,W011_G1B,W011_G1Atr,W011_G1_Dataset_pending)

#############################################################
#####            GARMENT 2 - WITH DERTERGENT            #####
#############################################################
#-----------------------------------------------------------#
#####                     W000_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G2<- read.csv('./Fibre count Summary/W000_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G2_B <- W000_G2%>% filter(grepl('_B.', Slice))
W000_G2_Atr <- W000_G2%>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G2_B and W000_G2_Atr
W000_G2_B$Slice<- gsub(".TIF","",W000_G2_B$Slice)
W000_G2_Atr$Slice<- gsub(".TIF","",W000_G2_Atr$Slice)

# Create table
W000_G2_Dataset_pending <- data.frame(rbind(W000_G2_B$Slice, W000_G2_B$Count, W000_G2_Atr$Count))
W000_G2_Dataset<-as.data.frame(t(W000_G2_Dataset_pending))
names(W000_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G2_Dataset[,2:3] = apply(W000_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G2,W000_G2_B,W000_G2_Atr,W000_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W001_G2                      ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G2 <- read.csv('./Fibre count Summary/W001_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G2B <- W001_G2 %>% filter(grepl('_B.', Slice))
W001_G2Atr <- W001_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G2B and W001_G2Atr
W001_G2B$Slice<- gsub(".TIF","",W001_G2B$Slice)
W001_G2Atr$Slice<- gsub(".TIF","",W001_G2Atr$Slice)

# Create table
W001_G2_Dataset_pending <- data.frame(rbind(W001_G2B$Slice, W001_G2B$Count, W001_G2Atr$Count))
W001_G2_Dataset<-as.data.frame(t(W001_G2_Dataset_pending))
names(W001_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G2_Dataset[,2:3] = apply(W001_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G2,W001_G2B,W001_G2Atr,W001_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W002_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G2 <- read.csv('./Fibre count Summary/W002_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G2B <- W002_G2 %>% filter(grepl('_B.', Slice))
W002_G2Atr <- W002_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G2B and W002_G2Atr
W002_G2B$Slice<- gsub(".TIF","",W002_G2B$Slice)
W002_G2Atr$Slice<- gsub(".TIF","",W002_G2Atr$Slice)

# Create table
W002_G2_Dataset_pending <- data.frame(rbind(W002_G2B$Slice, W002_G2B$Count, W002_G2Atr$Count))
W002_G2_Dataset<-as.data.frame(t(W002_G2_Dataset_pending))
names(W002_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G2_Dataset[,2:3] = apply(W002_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G2,W002_G2B,W002_G2Atr,W002_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W003_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G2 <- read.csv('./Fibre count Summary/W003_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G2B <- W003_G2 %>% filter(grepl('_B.', Slice))
W003_G2Atr <- W003_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G2B and W003_G2Atr
W003_G2B$Slice<- gsub(".TIF","",W003_G2B$Slice)
W003_G2Atr$Slice<- gsub(".TIF","",W003_G2Atr$Slice)

# Create table
W003_G2_Dataset_pending <- data.frame(rbind(W003_G2B$Slice, W003_G2B$Count, W003_G2Atr$Count))
W003_G2_Dataset<-as.data.frame(t(W003_G2_Dataset_pending))
names(W003_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G2_Dataset[,2:3] = apply(W003_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G2,W003_G2B,W003_G2Atr,W003_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W004_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G2 <- read.csv('./Fibre count Summary/W004_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G2B <- W004_G2 %>% filter(grepl('_B.', Slice))
W004_G2Atr <- W004_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G2B and W004_G2Atr
W004_G2B$Slice<- gsub(".TIF","",W004_G2B$Slice)
W004_G2Atr$Slice<- gsub(".TIF","",W004_G2Atr$Slice)

# Create table
W004_G2_Dataset_pending <- data.frame(rbind(W004_G2B$Slice, W004_G2B$Count, W004_G2Atr$Count))
W004_G2_Dataset<-as.data.frame(t(W004_G2_Dataset_pending))
names(W004_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G2_Dataset[,2:3] = apply(W004_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G2,W004_G2B,W004_G2Atr,W004_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W005_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G2 <- read.csv('./Fibre count Summary/W005_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G2B <- W005_G2 %>% filter(grepl('_B.', Slice))
W005_G2Atr <- W005_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G2B and W005_G2Atr
W005_G2B$Slice<- gsub(".TIF","",W005_G2B$Slice)
W005_G2Atr$Slice<- gsub(".TIF","",W005_G2Atr$Slice)

# Create table
W005_G2_Dataset_pending <- data.frame(rbind(W005_G2B$Slice, W005_G2B$Count, W005_G2Atr$Count))
W005_G2_Dataset<-as.data.frame(t(W005_G2_Dataset_pending))
names(W005_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G2_Dataset[,2:3] = apply(W005_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G2,W005_G2B,W005_G2Atr,W005_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W006_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G2 <- read.csv('./Fibre count Summary/W006_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G2B <- W006_G2 %>% filter(grepl('_B.', Slice))
W006_G2Atr <- W006_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G2B and W006_G2Atr
W006_G2B$Slice<- gsub(".TIF","",W006_G2B$Slice)
W006_G2Atr$Slice<- gsub(".TIF","",W006_G2Atr$Slice)

# Create table
W006_G2_Dataset_pending <- data.frame(rbind(W006_G2B$Slice, W006_G2B$Count, W006_G2Atr$Count))
W006_G2_Dataset<-as.data.frame(t(W006_G2_Dataset_pending))
names(W006_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G2_Dataset[,2:3] = apply(W006_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G2,W006_G2B,W006_G2Atr,W006_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W007_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W007_G2 <- read.csv('./Fibre count Summary/W007_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W007_G2B <- W007_G2 %>% filter(grepl('_B.', Slice))
W007_G2Atr <- W007_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W007_G2B and W007_G2Atr
W007_G2B$Slice<- gsub(".TIF","",W007_G2B$Slice)
W007_G2Atr$Slice<- gsub(".TIF","",W007_G2Atr$Slice)

# Create table
W007_G2_Dataset_pending <- data.frame(rbind(W007_G2B$Slice, W007_G2B$Count, W007_G2Atr$Count))
W007_G2_Dataset<-as.data.frame(t(W007_G2_Dataset_pending))
names(W007_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W007_G2_Dataset[,2:3] = apply(W007_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W007_G2,W007_G2B,W007_G2Atr,W007_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W008_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W008_G2 <- read.csv('./Fibre count Summary/W008_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W008_G2B <- W008_G2 %>% filter(grepl('_B.', Slice))
W008_G2Atr <- W008_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W008_G2B and W008_G2Atr
W008_G2B$Slice<- gsub(".TIF","",W008_G2B$Slice)
W008_G2Atr$Slice<- gsub(".TIF","",W008_G2Atr$Slice)

# Create table
W008_G2_Dataset_pending <- data.frame(rbind(W008_G2B$Slice, W008_G2B$Count, W008_G2Atr$Count))
W008_G2_Dataset<-as.data.frame(t(W008_G2_Dataset_pending))
names(W008_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W008_G2_Dataset[,2:3] = apply(W008_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W008_G2,W008_G2B,W008_G2Atr,W008_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W009_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W009_G2 <- read.csv('./Fibre count Summary/W009_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W009_G2B <- W009_G2 %>% filter(grepl('_B.', Slice))
W009_G2Atr <- W009_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W009_G2B and W009_G2Atr
W009_G2B$Slice<- gsub(".TIF","",W009_G2B$Slice)
W009_G2Atr$Slice<- gsub(".TIF","",W009_G2Atr$Slice)

# Create table
W009_G2_Dataset_pending <- data.frame(rbind(W009_G2B$Slice, W009_G2B$Count, W009_G2Atr$Count))
W009_G2_Dataset<-as.data.frame(t(W009_G2_Dataset_pending))
names(W009_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W009_G2_Dataset[,2:3] = apply(W009_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W009_G2,W009_G2B,W009_G2Atr,W009_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W010_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W010_G2 <- read.csv('./Fibre count Summary/W010_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W010_G2B <- W010_G2 %>% filter(grepl('_B.', Slice))
W010_G2Atr <- W010_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W010_G2B and W010_G2Atr
W010_G2B$Slice<- gsub(".TIF","",W010_G2B$Slice)
W010_G2Atr$Slice<- gsub(".TIF","",W010_G2Atr$Slice)

# Create table
W010_G2_Dataset_pending <- data.frame(rbind(W010_G2B$Slice, W010_G2B$Count, W010_G2Atr$Count))
W010_G2_Dataset<-as.data.frame(t(W010_G2_Dataset_pending))
names(W010_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W010_G2_Dataset[,2:3] = apply(W010_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W010_G2,W010_G2B,W010_G2Atr,W010_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W013_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W013_G2 <- read.csv('./Fibre count Summary/W013_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W013_G2B <- W013_G2 %>% filter(grepl('_B.', Slice))
W013_G2Atr <- W013_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W013_G2B and W013_G2Atr
W013_G2B$Slice<- gsub(".TIF","",W013_G2B$Slice)
W013_G2Atr$Slice<- gsub(".TIF","",W013_G2Atr$Slice)

# Create table
W013_G2_Dataset_pending <- data.frame(rbind(W013_G2B$Slice, W013_G2B$Count, W013_G2Atr$Count))
W013_G2_Dataset<-as.data.frame(t(W013_G2_Dataset_pending))
names(W013_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W013_G2_Dataset[,2:3] = apply(W013_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W013_G2,W013_G2B,W013_G2Atr,W013_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W015_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W015_G2 <- read.csv('./Fibre count Summary/W015_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W015_G2B <- W015_G2 %>% filter(grepl('_B.', Slice))
W015_G2Atr <- W015_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W015_G2B and W015_G2Atr
W015_G2B$Slice<- gsub(".TIF","",W015_G2B$Slice)
W015_G2Atr$Slice<- gsub(".TIF","",W015_G2Atr$Slice)

# Create table
W015_G2_Dataset_pending <- data.frame(rbind(W015_G2B$Slice, W015_G2B$Count, W015_G2Atr$Count))
W015_G2_Dataset<-as.data.frame(t(W015_G2_Dataset_pending))
names(W015_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W015_G2_Dataset[,2:3] = apply(W015_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W015_G2,W015_G2B,W015_G2Atr,W015_G2_Dataset_pending)

#############################################################
#####             GARMENT 3 - NO DERTERGENT             #####
#############################################################
#-----------------------------------------------------------#
#####                     W000_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G3 <- read.csv('./Fibre count Summary/W000_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G3B <- W000_G3 %>% filter(grepl('_B.', Slice))
W000_G3Atr <- W000_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G3B and W000_G3Atr
W000_G3B$Slice<- gsub(".TIF","",W000_G3B$Slice)
W000_G3Atr$Slice<- gsub(".TIF","",W000_G3Atr$Slice)

# Create table
W000_G3_Dataset_pending <- data.frame(rbind(W000_G3B$Slice, W000_G3B$Count, W000_G3Atr$Count))
W000_G3_Dataset<-as.data.frame(t(W000_G3_Dataset_pending))
names(W000_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G3_Dataset[,2:3] = apply(W000_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G3,W000_G3B,W000_G3Atr,W000_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W001_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G3 <- read.csv('./Fibre count Summary/W001_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G3B <- W001_G3 %>% filter(grepl('_B.', Slice))
W001_G3Atr <- W001_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G3B and W001_G3Atr
W001_G3B$Slice<- gsub(".TIF","",W001_G3B$Slice)
W001_G3Atr$Slice<- gsub(".TIF","",W001_G3Atr$Slice)

# Create table
W001_G3_Dataset_pending <- data.frame(rbind(W001_G3B$Slice, W001_G3B$Count, W001_G3Atr$Count))
W001_G3_Dataset<-as.data.frame(t(W001_G3_Dataset_pending))
names(W001_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G3_Dataset[,2:3] = apply(W001_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G3,W001_G3B,W001_G3Atr,W001_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W002_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G3 <- read.csv('./Fibre count Summary/W002_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G3B <- W002_G3 %>% filter(grepl('_B.', Slice))
W002_G3Atr <- W002_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G3B and W002_G3Atr
W002_G3B$Slice<- gsub(".TIF","",W002_G3B$Slice)
W002_G3Atr$Slice<- gsub(".TIF","",W002_G3Atr$Slice)

# Create table
W002_G3_Dataset_pending <- data.frame(rbind(W002_G3B$Slice, W002_G3B$Count, W002_G3Atr$Count))
W002_G3_Dataset<-as.data.frame(t(W002_G3_Dataset_pending))
names(W002_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G3_Dataset[,2:3] = apply(W002_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G3,W002_G3B,W002_G3Atr,W002_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W003_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G3 <- read.csv('./Fibre count Summary/W003_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G3B <- W003_G3 %>% filter(grepl('_B.', Slice))
W003_G3Atr <- W003_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G3B and W003_G3Atr
W003_G3B$Slice<- gsub(".TIF","",W003_G3B$Slice)
W003_G3Atr$Slice<- gsub(".TIF","",W003_G3Atr$Slice)

# Create table
W003_G3_Dataset_pending <- data.frame(rbind(W003_G3B$Slice, W003_G3B$Count, W003_G3Atr$Count))
W003_G3_Dataset<-as.data.frame(t(W003_G3_Dataset_pending))
names(W003_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G3_Dataset[,2:3] = apply(W003_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G3,W003_G3B,W003_G3Atr,W003_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W004_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G3 <- read.csv('./Fibre count Summary/W004_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G3B <- W004_G3 %>% filter(grepl('_B.', Slice))
W004_G3Atr <- W004_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G3B and W004_G3Atr
W004_G3B$Slice<- gsub(".TIF","",W004_G3B$Slice)
W004_G3Atr$Slice<- gsub(".TIF","",W004_G3Atr$Slice)

# Create table
W004_G3_Dataset_pending <- data.frame(rbind(W004_G3B$Slice, W004_G3B$Count, W004_G3Atr$Count))
W004_G3_Dataset<-as.data.frame(t(W004_G3_Dataset_pending))
names(W004_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G3_Dataset[,2:3] = apply(W004_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G3,W004_G3B,W004_G3Atr,W004_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W005_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G3 <- read.csv('./Fibre count Summary/W005_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G3B <- W005_G3 %>% filter(grepl('_B.', Slice))
W005_G3Atr <- W005_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G3B and W005_G3Atr
W005_G3B$Slice<- gsub(".TIF","",W005_G3B$Slice)
W005_G3Atr$Slice<- gsub(".TIF","",W005_G3Atr$Slice)

# Create table
W005_G3_Dataset_pending <- data.frame(rbind(W005_G3B$Slice, W005_G3B$Count, W005_G3Atr$Count))
W005_G3_Dataset<-as.data.frame(t(W005_G3_Dataset_pending))
names(W005_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G3_Dataset[,2:3] = apply(W005_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G3,W005_G3B,W005_G3Atr,W005_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W006_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G3 <- read.csv('./Fibre count Summary/W006_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G3B <- W006_G3 %>% filter(grepl('_B.', Slice))
W006_G3Atr <- W006_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G3B and W006_G3Atr
W006_G3B$Slice<- gsub(".TIF","",W006_G3B$Slice)
W006_G3Atr$Slice<- gsub(".TIF","",W006_G3Atr$Slice)

# Create table
W006_G3_Dataset_pending <- data.frame(rbind(W006_G3B$Slice, W006_G3B$Count, W006_G3Atr$Count))
W006_G3_Dataset<-as.data.frame(t(W006_G3_Dataset_pending))
names(W006_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G3_Dataset[,2:3] = apply(W006_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G3,W006_G3B,W006_G3Atr,W006_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W007_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W007_G3 <- read.csv('./Fibre count Summary/W007_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W007_G3B <- W007_G3 %>% filter(grepl('_B.', Slice))
W007_G3Atr <- W007_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W007_G3B and W007_G3Atr
W007_G3B$Slice<- gsub(".TIF","",W007_G3B$Slice)
W007_G3Atr$Slice<- gsub(".TIF","",W007_G3Atr$Slice)

# Create table
W007_G3_Dataset_pending <- data.frame(rbind(W007_G3B$Slice, W007_G3B$Count, W007_G3Atr$Count))
W007_G3_Dataset<-as.data.frame(t(W007_G3_Dataset_pending))
names(W007_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W007_G3_Dataset[,2:3] = apply(W007_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W007_G3,W007_G3B,W007_G3Atr,W007_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W008_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W008_G3 <- read.csv('./Fibre count Summary/W008_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W008_G3B <- W008_G3 %>% filter(grepl('_B.', Slice))
W008_G3Atr <- W008_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W008_G3B and W008_G3Atr
W008_G3B$Slice<- gsub(".TIF","",W008_G3B$Slice)
W008_G3Atr$Slice<- gsub(".TIF","",W008_G3Atr$Slice)

# Create table
W008_G3_Dataset_pending <- data.frame(rbind(W008_G3B$Slice, W008_G3B$Count, W008_G3Atr$Count))
W008_G3_Dataset<-as.data.frame(t(W008_G3_Dataset_pending))
names(W008_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W008_G3_Dataset[,2:3] = apply(W008_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W008_G3,W008_G3B,W008_G3Atr,W008_G3_Dataset_pending)

#-----------------------------------------------------------#
#####                     W009_G3                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W009_G3 <- read.csv('./Fibre count Summary/W009_G3_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W009_G3B <- W009_G3 %>% filter(grepl('_B.', Slice))
W009_G3Atr <- W009_G3 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W009_G3B and W009_G3Atr
W009_G3B$Slice<- gsub(".TIF","",W009_G3B$Slice)
W009_G3Atr$Slice<- gsub(".TIF","",W009_G3Atr$Slice)

# Create table
W009_G3_Dataset_pending <- data.frame(rbind(W009_G3B$Slice, W009_G3B$Count, W009_G3Atr$Count))
W009_G3_Dataset<-as.data.frame(t(W009_G3_Dataset_pending))
names(W009_G3_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W009_G3_Dataset[,2:3] = apply(W009_G3_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W009_G3,W009_G3B,W009_G3Atr,W009_G3_Dataset_pending)

#############################################################
#####                    GARMENT 4                      #####
#############################################################
#-----------------------------------------------------------#
#####                     W000_G4A                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G4A <- read.csv('./Fibre count Summary/W000_G4A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G4AB <- W000_G4A %>% filter(grepl('_B.', Slice))
W000_G4AAtr <- W000_G4A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G4AB and W000_G4AAtr
W000_G4AB$Slice<- gsub(".TIF","",W000_G4AB$Slice)
W000_G4AAtr$Slice<- gsub(".TIF","",W000_G4AAtr$Slice)

# Create table
W000_G4A_Dataset_pending <- data.frame(rbind(W000_G4AB$Slice, W000_G4AB$Count, W000_G4AAtr$Count))
W000_G4A_Dataset<-as.data.frame(t(W000_G4A_Dataset_pending))
names(W000_G4A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G4A_Dataset[,2:3] = apply(W000_G4A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G4A,W000_G4AB,W000_G4AAtr,W000_G4A_Dataset_pending)

#-----------------------------------------------------------#
#####                     W000_G4B                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G4B <- read.csv('./Fibre count Summary/W000_G4B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G4BB <- W000_G4B %>% filter(grepl('_B.', Slice))
W000_G4BAtr <- W000_G4B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G4BB and W000_G4BAtr
W000_G4BB$Slice<- gsub(".TIF","",W000_G4BB$Slice)
W000_G4BAtr$Slice<- gsub(".TIF","",W000_G4BAtr$Slice)

# Create table
W000_G4B_Dataset_pending <- data.frame(rbind(W000_G4BB$Slice, W000_G4BB$Count, W000_G4BAtr$Count))
W000_G4B_Dataset<-as.data.frame(t(W000_G4B_Dataset_pending))
names(W000_G4B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G4B_Dataset[,2:3] = apply(W000_G4B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G4B,W000_G4BB,W000_G4BAtr,W000_G4B_Dataset_pending)

#-----------------------------------------------------------#
#####                     W000_G4C                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G4C <- read.csv('./Fibre count Summary/W000_G4C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G4CB <- W000_G4C %>% filter(grepl('_B.', Slice))
W000_G4CAtr <- W000_G4C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G4CB and W000_G4CAtr
W000_G4CB$Slice<- gsub(".TIF","",W000_G4CB$Slice)
W000_G4CAtr$Slice<- gsub(".TIF","",W000_G4CAtr$Slice)

# Create table
W000_G4C_Dataset_pending <- data.frame(rbind(W000_G4CB$Slice, W000_G4CB$Count, W000_G4CAtr$Count))
W000_G4C_Dataset<-as.data.frame(t(W000_G4C_Dataset_pending))
names(W000_G4C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G4C_Dataset[,2:3] = apply(W000_G4C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G4C,W000_G4CB,W000_G4CAtr,W000_G4C_Dataset_pending)
