#############################################################
#####                    Data upload                    #####
#############################################################
# This code is to upload the data related to the number of fibres generated by ImageJ
# The .csv file to upload will need to have the following columns:
# Slice; Count;
# "Count" correspond to the fibre counted by imageJ

# "Slice" correspond to the name of the receiver swatch and must be written in this form "W000_G1_G3_8_perp_B.TIF" for the wash experiments
# with Wxxx the wash number, Gx the garment number, "_x_" the contact area number and "_B" the condition of the experimentr
# condition experiments: "B" for Before transfer, "Atr" for after transfer

#############################################################
#####             GARMENT 1 - NO DERTERGENT             #####
#############################################################
#-----------------------------------------------------------#
#####                     W000_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G1 <- read.csv('./Fibre count Summary/W000_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G1B <- W000_G1 %>% filter(grepl('_B.', Slice))
W000_G1Atr <- W000_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G1B and W000_G1Atr
W000_G1B$Slice<- gsub(".TIF","",W000_G1B$Slice)
W000_G1Atr$Slice<- gsub(".TIF","",W000_G1Atr$Slice)

# Create table
W000_G1_Dataset_pending <- data.frame(rbind(W000_G1B$Slice, W000_G1B$Count, W000_G1Atr$Count))
W000_G1_Dataset<-as.data.frame(t(W000_G1_Dataset_pending))
names(W000_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G1_Dataset[,2:3] = apply(W000_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G1,W000_G1B,W000_G1Atr,W000_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W001_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G1 <- read.csv('./Fibre count Summary/W001_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G1B <- W001_G1 %>% filter(grepl('_B.', Slice))
W001_G1Atr <- W001_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G1B and W001_G1Atr
W001_G1B$Slice<- gsub(".TIF","",W001_G1B$Slice)
W001_G1Atr$Slice<- gsub(".TIF","",W001_G1Atr$Slice)

# Create table
W001_G1_Dataset_pending <- data.frame(rbind(W001_G1B$Slice, W001_G1B$Count, W001_G1Atr$Count))
W001_G1_Dataset<-as.data.frame(t(W001_G1_Dataset_pending))
names(W001_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G1_Dataset[,2:3] = apply(W001_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G1,W001_G1B,W001_G1Atr,W001_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W002_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G1 <- read.csv('./Fibre count Summary/W002_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G1B <- W002_G1 %>% filter(grepl('_B.', Slice))
W002_G1Atr <- W002_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G1B and W002_G1Atr
W002_G1B$Slice<- gsub(".TIF","",W002_G1B$Slice)
W002_G1Atr$Slice<- gsub(".TIF","",W002_G1Atr$Slice)

# Create table
W002_G1_Dataset_pending <- data.frame(rbind(W002_G1B$Slice, W002_G1B$Count, W002_G1Atr$Count))
W002_G1_Dataset<-as.data.frame(t(W002_G1_Dataset_pending))
names(W002_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G1_Dataset[,2:3] = apply(W002_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G1,W002_G1B,W002_G1Atr,W002_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W003_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G1 <- read.csv('./Fibre count Summary/W003_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G1B <- W003_G1 %>% filter(grepl('_B.', Slice))
W003_G1Atr <- W003_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G1B and W003_G1Atr
W003_G1B$Slice<- gsub(".TIF","",W003_G1B$Slice)
W003_G1Atr$Slice<- gsub(".TIF","",W003_G1Atr$Slice)

# Create table
W003_G1_Dataset_pending <- data.frame(rbind(W003_G1B$Slice, W003_G1B$Count, W003_G1Atr$Count))
W003_G1_Dataset<-as.data.frame(t(W003_G1_Dataset_pending))
names(W003_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G1_Dataset[,2:3] = apply(W003_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G1,W003_G1B,W003_G1Atr,W003_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W004_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G1 <- read.csv('./Fibre count Summary/W004_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G1B <- W004_G1 %>% filter(grepl('_B.', Slice))
W004_G1Atr <- W004_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G1B and W004_G1Atr
W004_G1B$Slice<- gsub(".TIF","",W004_G1B$Slice)
W004_G1Atr$Slice<- gsub(".TIF","",W004_G1Atr$Slice)

# Create table
W004_G1_Dataset_pending <- data.frame(rbind(W004_G1B$Slice, W004_G1B$Count, W004_G1Atr$Count))
W004_G1_Dataset<-as.data.frame(t(W004_G1_Dataset_pending))
names(W004_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G1_Dataset[,2:3] = apply(W004_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G1,W004_G1B,W004_G1Atr,W004_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W005_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G1 <- read.csv('./Fibre count Summary/W005_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G1B <- W005_G1 %>% filter(grepl('_B.', Slice))
W005_G1Atr <- W005_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G1B and W005_G1Atr
W005_G1B$Slice<- gsub(".TIF","",W005_G1B$Slice)
W005_G1Atr$Slice<- gsub(".TIF","",W005_G1Atr$Slice)

# Create table
W005_G1_Dataset_pending <- data.frame(rbind(W005_G1B$Slice, W005_G1B$Count, W005_G1Atr$Count))
W005_G1_Dataset<-as.data.frame(t(W005_G1_Dataset_pending))
names(W005_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G1_Dataset[,2:3] = apply(W005_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G1,W005_G1B,W005_G1Atr,W005_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W006_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G1 <- read.csv('./Fibre count Summary/W006_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G1B <- W006_G1 %>% filter(grepl('_B.', Slice))
W006_G1Atr <- W006_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G1B and W006_G1Atr
W006_G1B$Slice<- gsub(".TIF","",W006_G1B$Slice)
W006_G1Atr$Slice<- gsub(".TIF","",W006_G1Atr$Slice)

# Create table
W006_G1_Dataset_pending <- data.frame(rbind(W006_G1B$Slice, W006_G1B$Count, W006_G1Atr$Count))
W006_G1_Dataset<-as.data.frame(t(W006_G1_Dataset_pending))
names(W006_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G1_Dataset[,2:3] = apply(W006_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G1,W006_G1B,W006_G1Atr,W006_G1_Dataset_pending)

#-----------------------------------------------------------#
#####                     W007_G1                        ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W007_G1 <- read.csv('./Fibre count Summary/W007_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W007_G1B <- W007_G1 %>% filter(grepl('_B.', Slice))
W007_G1Atr <- W007_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W007_G1B and W007_G1Atr
W007_G1B$Slice<- gsub(".TIF","",W007_G1B$Slice)
W007_G1Atr$Slice<- gsub(".TIF","",W007_G1Atr$Slice)

# Create table
W007_G1_Dataset_pending <- data.frame(rbind(W007_G1B$Slice, W007_G1B$Count, W007_G1Atr$Count))
W007_G1_Dataset<-as.data.frame(t(W007_G1_Dataset_pending))
names(W007_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W007_G1_Dataset[,2:3] = apply(W007_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W007_G1,W007_G1B,W007_G1Atr,W007_G1_Dataset_pending)

#############################################################
#####            GARMENT 2 - WITH DERTERGENT            #####
#############################################################
#-----------------------------------------------------------#
#####                     W000_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G2<- read.csv('./Fibre count Summary/W000_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G2_B <- W000_G2%>% filter(grepl('_B.', Slice))
W000_G2_Atr <- W000_G2%>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G2_B and W000_G2_Atr
W000_G2_B$Slice<- gsub(".TIF","",W000_G2_B$Slice)
W000_G2_Atr$Slice<- gsub(".TIF","",W000_G2_Atr$Slice)

# Create table
W000_G2_Dataset_pending <- data.frame(rbind(W000_G2_B$Slice, W000_G2_B$Count, W000_G2_Atr$Count))
W000_G2_Dataset<-as.data.frame(t(W000_G2_Dataset_pending))
names(W000_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G2_Dataset[,2:3] = apply(W000_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G2,W000_G2_B,W000_G2_Atr,W000_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W001_G2                      ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G2 <- read.csv('./Fibre count Summary/W001_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G2B <- W001_G2 %>% filter(grepl('_B.', Slice))
W001_G2Atr <- W001_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G2B and W001_G2Atr
W001_G2B$Slice<- gsub(".TIF","",W001_G2B$Slice)
W001_G2Atr$Slice<- gsub(".TIF","",W001_G2Atr$Slice)

# Create table
W001_G2_Dataset_pending <- data.frame(rbind(W001_G2B$Slice, W001_G2B$Count, W001_G2Atr$Count))
W001_G2_Dataset<-as.data.frame(t(W001_G2_Dataset_pending))
names(W001_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G2_Dataset[,2:3] = apply(W001_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G2,W001_G2B,W001_G2Atr,W001_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W002_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G2 <- read.csv('./Fibre count Summary/W002_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G2B <- W002_G2 %>% filter(grepl('_B.', Slice))
W002_G2Atr <- W002_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G2B and W002_G2Atr
W002_G2B$Slice<- gsub(".TIF","",W002_G2B$Slice)
W002_G2Atr$Slice<- gsub(".TIF","",W002_G2Atr$Slice)

# Create table
W002_G2_Dataset_pending <- data.frame(rbind(W002_G2B$Slice, W002_G2B$Count, W002_G2Atr$Count))
W002_G2_Dataset<-as.data.frame(t(W002_G2_Dataset_pending))
names(W002_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G2_Dataset[,2:3] = apply(W002_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G2,W002_G2B,W002_G2Atr,W002_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W003_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G2 <- read.csv('./Fibre count Summary/W003_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G2B <- W003_G2 %>% filter(grepl('_B.', Slice))
W003_G2Atr <- W003_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G2B and W003_G2Atr
W003_G2B$Slice<- gsub(".TIF","",W003_G2B$Slice)
W003_G2Atr$Slice<- gsub(".TIF","",W003_G2Atr$Slice)

# Create table
W003_G2_Dataset_pending <- data.frame(rbind(W003_G2B$Slice, W003_G2B$Count, W003_G2Atr$Count))
W003_G2_Dataset<-as.data.frame(t(W003_G2_Dataset_pending))
names(W003_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G2_Dataset[,2:3] = apply(W003_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G2,W003_G2B,W003_G2Atr,W003_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W004_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G2 <- read.csv('./Fibre count Summary/W004_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G2B <- W004_G2 %>% filter(grepl('_B.', Slice))
W004_G2Atr <- W004_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G2B and W004_G2Atr
W004_G2B$Slice<- gsub(".TIF","",W004_G2B$Slice)
W004_G2Atr$Slice<- gsub(".TIF","",W004_G2Atr$Slice)

# Create table
W004_G2_Dataset_pending <- data.frame(rbind(W004_G2B$Slice, W004_G2B$Count, W004_G2Atr$Count))
W004_G2_Dataset<-as.data.frame(t(W004_G2_Dataset_pending))
names(W004_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G2_Dataset[,2:3] = apply(W004_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G2,W004_G2B,W004_G2Atr,W004_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W005_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G2 <- read.csv('./Fibre count Summary/W005_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G2B <- W005_G2 %>% filter(grepl('_B.', Slice))
W005_G2Atr <- W005_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G2B and W005_G2Atr
W005_G2B$Slice<- gsub(".TIF","",W005_G2B$Slice)
W005_G2Atr$Slice<- gsub(".TIF","",W005_G2Atr$Slice)

# Create table
W005_G2_Dataset_pending <- data.frame(rbind(W005_G2B$Slice, W005_G2B$Count, W005_G2Atr$Count))
W005_G2_Dataset<-as.data.frame(t(W005_G2_Dataset_pending))
names(W005_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G2_Dataset[,2:3] = apply(W005_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G2,W005_G2B,W005_G2Atr,W005_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W006_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G2 <- read.csv('./Fibre count Summary/W006_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G2B <- W006_G2 %>% filter(grepl('_B.', Slice))
W006_G2Atr <- W006_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G2B and W006_G2Atr
W006_G2B$Slice<- gsub(".TIF","",W006_G2B$Slice)
W006_G2Atr$Slice<- gsub(".TIF","",W006_G2Atr$Slice)

# Create table
W006_G2_Dataset_pending <- data.frame(rbind(W006_G2B$Slice, W006_G2B$Count, W006_G2Atr$Count))
W006_G2_Dataset<-as.data.frame(t(W006_G2_Dataset_pending))
names(W006_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G2_Dataset[,2:3] = apply(W006_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G2,W006_G2B,W006_G2Atr,W006_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W007_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W007_G2 <- read.csv('./Fibre count Summary/W007_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W007_G2B <- W007_G2 %>% filter(grepl('_B.', Slice))
W007_G2Atr <- W007_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W007_G2B and W007_G2Atr
W007_G2B$Slice<- gsub(".TIF","",W007_G2B$Slice)
W007_G2Atr$Slice<- gsub(".TIF","",W007_G2Atr$Slice)

# Create table
W007_G2_Dataset_pending <- data.frame(rbind(W007_G2B$Slice, W007_G2B$Count, W007_G2Atr$Count))
W007_G2_Dataset<-as.data.frame(t(W007_G2_Dataset_pending))
names(W007_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W007_G2_Dataset[,2:3] = apply(W007_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W007_G2,W007_G2B,W007_G2Atr,W007_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W008_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W008_G2 <- read.csv('./Fibre count Summary/W008_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W008_G2B <- W008_G2 %>% filter(grepl('_B.', Slice))
W008_G2Atr <- W008_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W008_G2B and W008_G2Atr
W008_G2B$Slice<- gsub(".TIF","",W008_G2B$Slice)
W008_G2Atr$Slice<- gsub(".TIF","",W008_G2Atr$Slice)

# Create table
W008_G2_Dataset_pending <- data.frame(rbind(W008_G2B$Slice, W008_G2B$Count, W008_G2Atr$Count))
W008_G2_Dataset<-as.data.frame(t(W008_G2_Dataset_pending))
names(W008_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W008_G2_Dataset[,2:3] = apply(W008_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W008_G2,W008_G2B,W008_G2Atr,W008_G2_Dataset_pending)

#-----------------------------------------------------------#
#####                     W009_G2                       ####
#-----------------------------------------------------------#
###_________________Data loading_________________###
W009_G2 <- read.csv('./Fibre count Summary/W009_G2_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W009_G2B <- W009_G2 %>% filter(grepl('_B.', Slice))
W009_G2Atr <- W009_G2 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W009_G2B and W009_G2Atr
W009_G2B$Slice<- gsub(".TIF","",W009_G2B$Slice)
W009_G2Atr$Slice<- gsub(".TIF","",W009_G2Atr$Slice)

# Create table
W009_G2_Dataset_pending <- data.frame(rbind(W009_G2B$Slice, W009_G2B$Count, W009_G2Atr$Count))
W009_G2_Dataset<-as.data.frame(t(W009_G2_Dataset_pending))
names(W009_G2_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W009_G2_Dataset[,2:3] = apply(W009_G2_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W009_G2,W009_G2B,W009_G2Atr,W009_G2_Dataset_pending)
